name: LightChat
version: '1.0'
main: com.memestealer.lightchat.LightChat
api-version: 1.18
authors: [ MEMESTEALER ]
description: A Simple and Lightweight Chat Format.
commands:
  lcreload:
    description: Reload the configuration & other related yml files.
  lcaddword:
    description: Add a new word to filter word yml.
softdepend:
  - PlaceholderAPI